### ISSUE TITLE
Issue when adding approvals to a project

### ISSUE THREAD

**Issue by SeanFarrow** [approvals/ApprovalTests.Java#45]
I'm trying to use the combination approvals functionality with a lambda function from eclipse and am not using maven for this project.
When I use the lambda, I get an error that org.lambda.function.function2 cannot be found. I've downloaded the approvals jar file, but it appers it's looking for more.

Is there a jar file with everything in? or can I build one?
Cheers
Sean.

**Comment by isidore** [comment]
Ah, I think the issue is the 'downloading jar' part. ApprovalTests has a dependency on ApprovalUtils
https://search.maven.org/artifact/com.approvaltests/approvaltests-util/2.0.2/jar
This is automatically handled with maven, but would need to be downloaded separately if you are downloading.

I'm not sure how to resolve this. Probably this is a documentation issue, but it does open the 'other dependencies' door.
