### ISSUE TITLE
Broken links on README

### ISSUE THREAD

**Issue by jesuswasrasta** [approvals/ApprovalTests.Java#54]
These links on **More Info** section are broken:

* Blog
* Getting Started Doc

**Comment by juniormichieletto** [comment]
Hello :)
I was taking a look at the readme and I noticed two things.
1. The blog link if working now.
2. The "Getting Started Doc" is still broken(More Info > Getting Started Doc),
but what do you thing in remove this one?
Since already exist a simple "Getting start" self-contained into the main README... (https://github.com/approvals/ApprovalTests.Java#getting-started)

**Comment by SimonCropp** [comment]
removed getting started and blog (since it is no longer being used)
